"""
humpback_data.py
Fetches humpback whale (Megaptera novaeangliae) occurrence records from GBIF
and writes humpback_data.js for use in humpback.html.

Run: python3 humpback_data.py
Data source: Global Biodiversity Information Facility (gbif.org)
"""

import requests
import json
import time

TAXON_KEY = 5220086  # Megaptera novaeangliae — confirmed via GBIF species/match

# GBIF dataset keys
DS_LOGBOOK      = "01d9d254"  # Historical distribution of whales from logbooks, 1785–1913
DS_EARLY_NZ     = "7d122ae7"  # Humpback whale sightings around New Zealand, 1970–1999
DS_HAPPYWHALE   = "519461fd"  # Happywhale – Humpback whale in South Pacific Ocean
DS_INATURALIST  = "50c9509d"  # iNaturalist Research-grade Observations

NZ_LAT_MIN, NZ_LAT_MAX = -52, -30
NZ_LON_MIN, NZ_LON_MAX = 163, 180


BASE = "https://api.gbif.org/v1/occurrence/search"


def fetch_gbif(qs_extra="", max_records=300, **params):
    """Paginate through GBIF occurrence search.
    Pass extra raw query string params (e.g. year ranges) via qs_extra.
    """
    records = []
    offset = 0
    while len(records) < max_records:
        batch_size = min(300, max_records - len(records))
        # Build URL manually to avoid requests encoding commas in range params
        qs = "&".join(f"{k}={v}" for k, v in {**params, "limit": batch_size, "offset": offset}.items())
        if qs_extra:
            qs += "&" + qs_extra
        resp = requests.get(f"{BASE}?{qs}", timeout=30)
        resp.raise_for_status()
        data = resp.json()
        batch = data.get("results", [])
        if not batch:
            break
        records.extend(batch)
        total = min(max_records, data.get("count", len(records)))
        print(f"  fetched {len(records)}/{total}", end="\r", flush=True)
        if data.get("endOfRecords", True):
            break
        offset += len(batch)
        time.sleep(0.25)
    print()
    return records


def to_point(r, bbox=True):
    """Extract minimal lat/lon/year/month from a GBIF occurrence record.
    If bbox=True, filter to the NZ bounding box."""
    lat = r.get("decimalLatitude")
    lon = r.get("decimalLongitude")
    if lat is None or lon is None:
        return None
    lat, lon = float(lat), float(lon)
    if bbox and not (NZ_LAT_MIN <= lat <= NZ_LAT_MAX and NZ_LON_MIN <= lon <= NZ_LON_MAX):
        return None
    return {
        "lat": round(lat, 4),
        "lon": round(lon, 4),
        "year": r.get("year"),
        "month": r.get("month"),
    }


def clean_records(raw, bbox=True):
    result = []
    for r in raw:
        p = to_point(r, bbox=bbox)
        if p is not None:
            result.append(p)
    return result


# All three eras: use year range in raw query string to avoid %2C encoding issue
print("Fetching early recovery sightings (1970–1999)...")
early_raw = fetch_gbif(
    qs_extra="year=1970,1999",
    max_records=300,
    taxonKey=TAXON_KEY,
    country="NZ",
    hasCoordinate="true",
)
early = clean_records(early_raw, bbox=False)
print(f"  → {len(early)} records")

print("Fetching modern sightings (2000–present)...")
modern_raw = fetch_gbif(
    qs_extra="year=2000,2026",
    max_records=600,
    taxonKey=TAXON_KEY,
    country="NZ",
    hasCoordinate="true",
)
# Deduplicate by lat/lon/year
seen = set()
modern = []
for r in modern_raw:
    p = to_point(r, bbox=False)
    if p is None:
        continue
    key = (p["lat"], p["lon"], p["year"])
    if key not in seen:
        seen.add(key)
        modern.append(p)
print(f"  → {len(modern)} unique records")

# Logbook (pre-1950) — skip unreliable dataset key; use empty list
# Steps 1 & 2 show whaling station markers and circles, not sighting dots
logbook = []


# ── Write humpback_data.js ────────────────────────────────────────────────────
lines = [
    "// Generated by humpback_data.py — do not edit manually",
    "// Source: Global Biodiversity Information Facility (gbif.org)",
    "",
    "var SIGHTINGS_LOGBOOK = " + json.dumps(logbook, separators=(",", ":")) + ";",
    "",
    "var SIGHTINGS_EARLY = " + json.dumps(early, separators=(",", ":")) + ";",
    "",
    "var SIGHTINGS_MODERN = " + json.dumps(modern, separators=(",", ":")) + ";",
    "",
]

with open("humpback_data.js", "w") as f:
    f.write("\n".join(lines))

print(f"\nSaved → humpback_data.js")
print(f"  Logbook: {len(logbook)}  |  Early (1970–99): {len(early)}  |  Modern (2000+): {len(modern)}")
